### PR TITLE
First day of week should be a usersetting

### PR DESCRIPTION
**Pull request by sanderboom**
Hi Brandon!

Where I'm from weeks start on Monday, so I scratched the itch and I messed around a bit with your Svelte/ts/js potpourri :wink:

The PR:
- adds a setting `firstDayOfWeek` under meta,
- a slide for during initial setup,
- a setting element under Tweaks,
- 3 new localized strings,
- and `calender.svelte` and `sweet.svelte` use the setting instead of the hardcoded value 

`day-time-grid.svelte` is quite messy and you probably have a better way to do this - I'm also not sure whether you would appreciate a refactor from using 1 for Sunday, 2 for Monday (as you use) to 0 and 1 :wink: So not ready for merge yet.

BTW dashboards are looking good! 🤘 

Cheers

### CODE REVIEW

**Comment by brandoncorbin** [comment]
This is great! I'm going to push 5.3 tomorrow I think and once that's done I'll get this merged in so its part of the next patch release.

**Comment by brandoncorbin** [comment]
Never mind! It's getting pulled now!

**Comment by sanderboom** [comment]
Ha, nice :rocket:  
You *did* check & test, right (especially `day-time-grid.svelte`)? First `svelte` stuff I did :wink:

**Comment by brandoncorbin** [comment]
I did, and it looks good, nice job

**Pull request merged**
